version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: pserve ./food-is-mood/dev.ini --reload
    volumes:
      - .:/code
    ports:
      - "6543:6543"
    depends_on:
      - db
